on:
  push:
    branches:
      - main
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
  # build-deploy:
    # runs-on: ubuntu-latest
    # steps:
      # - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      # - uses: actions/checkout@v2
      # - uses: actions/setup-python@v2
      # - uses: aws-actions/setup-sam@v1
      # - uses: aws-actions/configure-aws-credentials@v1
        # with:
          # aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          # aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # aws-region: us-west-2
      # sam build 
      # - run: sam build --use-container

# Run Unit tests- Specify unit tests here 

# sam deploy
      # - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name sam-hello-world --s3-bucket my-bucket-8063 --capabilities CAPABILITY_IAM --region us-west-2




      
