on:
  workflow_call: # allows calling this workflow from another workflow
    secrets:
      AWS_ACCESS_KEY_ID: { required: true }
      AWS_SECRET_ACCESS_KEY: { required: true }
  push:
    branches:
      - master
# permissions:
#       id-token: write   # This is required for requesting the JWT
#       contents: read  
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "Testing vars in Github ${{ github.env.MY_VARIABLE }}"
      - run: echo "observing secrets AWS_ACCESS_KEY_ID- ${{ secrets.AWS_ACCESS_KEY_ID }} AWS_SECRET_ACCESS_KEY- ${{ secrets.AWS_SECRET_ACCESS_KEY }}"
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      # sam build 
      - run: ls -lah
      - run: echo "WORKSPACE - ${{ github.workspace }}"
      - run: sam build --use-container --template-file  /home/runner/work/first_aws_lambda/github-actions-with-aws-sam/template.yml

# Run Unit tests- Specify unit tests here 

# sam deploy
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name sam-hello-world --s3-bucket my-bucket-8063 --capabilities CAPABILITY_IAM --region us-west-2




      
